/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rampoly_RMS;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ahmadintech
 */
public class Starter extends javax.swing.JFrame {
Connection conn;
    /**
     * Creates new form Starter
     */
    public Starter() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        conn = ConnectMe.SQL();
        showDepList();
        popup.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        popup = new javax.swing.JInternalFrame();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDepname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDepCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CBdepList = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RAMAT POLYTECHNIC MAIDUGURI");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        popup.setTitle("ADD NEW");
        popup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        popup.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        popup.setVisible(true);
        popup.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        popup.getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 140, 160, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Department");
        popup.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));
        popup.getContentPane().add(txtDepname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 306, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Depart. Code:");
        popup.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));
        popup.getContentPane().add(txtDepCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 306, 35));

        jPanel1.add(popup);
        popup.setBounds(370, 10, 560, 230);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SELECT DEPARTMENT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 220, 156, 17);

        CBdepList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CBdepList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEPARTMENT" }));
        jPanel1.add(CBdepList);
        CBdepList.setBounds(530, 200, 325, 45);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD NEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 290, 150, 36);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("CONTINUE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(700, 290, 157, 36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void showDepList(){
    String Query = "SELECT Dep_sort FROM DEPARTMENT";
    Statement st;
    try {
        st = conn.createStatement();
        ResultSet rs = st.executeQuery(Query);
        while(rs.next()){
            CBdepList.addItem(rs.getString(1));
        }
    } catch (SQLException ex) {
        Logger.getLogger(Starter.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        popup.setVisible(true);
 
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if("".equals(txtDepname.getText().trim())){
            JOptionPane.showMessageDialog(rootPane, "Field is required");
        }else if("".equals(txtDepCode.getText().trim())){
            JOptionPane.showMessageDialog(rootPane, "Field is required");
        }else{
        push();
        showDepList();
        popup.dispose();
        jButton2.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed
private void Activator(){
    String active = "UPDATE Settings SET first_lunch = 'true'";
    try {
        PreparedStatement activate = conn.prepareStatement(active);
        activate.execute();
    } catch (SQLException ex) {
        Logger.getLogger(Starter.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(CBdepList.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "No Department Selected.");
        }else{
        Activator();
        Add_new_Student frame = new Add_new_Student();
        frame.setVisible(true);
        this.dispose();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
                
         
    }//GEN-LAST:event_formWindowActivated
private void push(){
Date now = new Date();
SimpleDateFormat fd = new SimpleDateFormat("dd/MM/yyyy");

String SQL = "INSERT INTO DEPARTMENT (dep_name, Dep_sort, date_added)VALUES(?,?,?)";
PreparedStatement ps;
PreparedStatement ps1;
try {
ps = conn.prepareStatement(SQL);
ps.setString(1, txtDepname.getText().toUpperCase());
ps.setString(2, txtDepCode.getText().toUpperCase());
ps.setString(3, fd.format(now));
ps.executeUpdate();

ps1 = conn.prepareStatement("UPDATE Settings SET d_dep = ?");
ps1.setString(1, txtDepCode.getText().toUpperCase());
ps1.executeUpdate();

ps.close();
ps1.close();
} catch (Exception e) {
    System.err.println(e);
}

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Starter().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBdepList;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JInternalFrame popup;
    private javax.swing.JTextField txtDepCode;
    private javax.swing.JTextField txtDepname;
    // End of variables declaration//GEN-END:variables
}
